- name: Raspberry Pi 3
  hosts: pi3
  roles:
    - role: escalate.raspberry.cmdline
      tags: cmdline
    - role: escalate.raspberry.common
      tags: common
    - role: escalate.raspberry.swap
      tags: swap
    - role: escalate.raspberry.cron
      tags: cron
    - role: escalate.raspberry.locale
      tags: locale
    - role: escalate.raspberry.systemd_timesyncd
      tags: timesyncd
