roles:
  # https://galaxy.ansible.com/ui/standalone/roles/escalate/cmdline/
  - name: cmdline
    src: escalate.cmdline
    version: v3.0.0

  # https://galaxy.ansible.com/ui/standalone/roles/escalate/common/
  - name: common
    src: escalate.common
    version: v2.1.0

  # https://galaxy.ansible.com/ui/standalone/roles/escalate/cron/
  - name: cron
    src: escalate.cron
    version: v2.1.0

collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  - name: community.general
    version: 10.7.2
